import type { Metadata } from "next";

export const metadata: Metadata = { title: "Employee Engagement Assessment | Incetric Engage", description: "Ukur keterlibatan karyawan melalui 12 sinyal utama dan temukan prioritas yang mendorong pertumbuhan organisasi." };

const impacts = [["78%", "lebih sedikit", "ketidakhadiran"], ["23%", "lebih tinggi", "profitabilitas"], ["18%", "lebih tinggi", "penjualan"], ["14%", "lebih tinggi", "produktivitas"]];
const pillars = [
  { number: "01", name: "Kebutuhan Dasar", label: "Fondasi untuk bekerja", copy: "Karyawan bisa fokus memberi hasil terbaik ketika arah kerja jelas dan semua kebutuhan untuk bekerja tersedia.", qs: [["Q1", "Ekspektasi yang jelas"], ["Q2", "Dukungan kerja yang memadai"]] },
  { number: "02", name: "Kontribusi Individu", label: "Ruang untuk berkontribusi", copy: "Karyawan lebih terlibat saat dapat mengandalkan kekuatan terbaiknya dan merasa kontribusinya sungguh dihargai.", qs: [["Q3", "Pemanfaatan kekuatan"], ["Q4", "Apresiasi yang bermakna"]] },
  { number: "03", name: "Kebersamaan Tim", label: "Koneksi dan kolaborasi", copy: "Rasa peduli, suara yang didengar, dan tujuan bersama membangun tim yang saling percaya dan mau bergerak lebih jauh.", qs: [["Q5", "Kepedulian"], ["Q6", "Dukungan untuk berkembang"], ["Q7", "Suara yang didengar"], ["Q8", "Tujuan bersama"], ["Q9", "Komitmen pada kualitas"], ["Q10", "Kedekatan antarrekan"]] },
  { number: "04", name: "Pertumbuhan", label: "Perjalanan ke depan", copy: "Percakapan yang jujur tentang kemajuan dan kesempatan belajar membuat talenta melihat masa depan bersama organisasi.", qs: [["Q11", "Percakapan perkembangan"], ["Q12", "Kesempatan untuk bertumbuh"]] },
];
const signalGroups = [
  { number: "01", title: "Kebutuhan Dasar", subtitle: "Arah dan dukungan untuk bekerja optimal", items: [
    ["Q1", "Ekspektasi yang Jelas", "Saya memahami hasil, tanggung jawab, dan prioritas yang diharapkan dari saya."],
    ["Q2", "Dukungan Kerja yang Memadai", "Saya memiliki perangkat, informasi, dan dukungan yang dibutuhkan untuk menghasilkan pekerjaan terbaik."],
  ]},
  { number: "02", title: "Kontribusi Individu", subtitle: "Kesempatan memberi yang terbaik dan merasa dihargai", items: [
    ["Q3", "Ruang untuk Mengandalkan Kekuatan", "Dalam pekerjaan sehari-hari, saya punya kesempatan untuk menggunakan kemampuan terbaik saya."],
    ["Q4", "Apresiasi yang Bermakna", "Kontribusi yang saya berikan mendapat pengakuan dan apresiasi yang tulus."],
  ]},
  { number: "03", title: "Kebersamaan Tim", subtitle: "Hubungan yang membuat orang merasa didengar dan terhubung", items: [
    ["Q5", "Kepedulian sebagai Individu", "Atasan atau rekan kerja menunjukkan kepedulian kepada saya, bukan hanya pada hasil pekerjaan saya."],
    ["Q6", "Dukungan untuk Berkembang", "Ada seseorang di tempat kerja yang aktif mendorong saya untuk terus maju dan berkembang."],
    ["Q7", "Suara yang Didengar", "Pendapat saya didengar dan sungguh dipertimbangkan dalam keputusan yang relevan."],
    ["Q8", "Tujuan yang Bermakna", "Misi organisasi membuat saya melihat arti dan dampak dari pekerjaan yang saya lakukan."],
    ["Q9", "Komitmen pada Kualitas", "Rekan-rekan saya memiliki standar dan komitmen yang sama untuk menghasilkan pekerjaan berkualitas."],
    ["Q10", "Kedekatan Antar-rekan", "Saya memiliki hubungan yang dekat dan saling percaya dengan orang-orang di tempat kerja."],
  ]},
  { number: "04", title: "Pertumbuhan", subtitle: "Percakapan dan peluang yang membuka masa depan", items: [
    ["Q11", "Percakapan tentang Perkembangan", "Dalam enam bulan terakhir, ada percakapan yang membantu saya memahami kemajuan dan langkah pengembangan berikutnya."],
    ["Q12", "Kesempatan untuk Terus Bertumbuh", "Dalam setahun terakhir, saya mendapatkan kesempatan yang berarti untuk belajar dan mengembangkan diri."],
  ]},
];

export default function Home() {
  return <main>
    <nav className="nav-shell" aria-label="Navigasi utama"><a className="brand" href="#top" aria-label="Incentric Engage beranda"><span className="brand-mark">i</span><span>incentric <b>engage</b></span></a><div className="nav-links"><a href="#manfaat">Manfaat</a><a href="#framework">Framework</a><a href="#insight">Insight</a></div><a className="button button-small" href="#contact">Jadwalkan Demo</a></nav>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span /> Employee Engagement Assessment</p><h1>Bangun tim yang<br />hadir sepenuhnya.</h1><p className="hero-lede">Pahami apa yang benar-benar dirasakan karyawan. Ubah 12 sinyal engagement menjadi keputusan yang lebih tajam—dan tempat kerja yang membuat talenta terbaik ingin bertumbuh.</p><div className="hero-actions"><a className="button" href="#contact">Mulai Assessment <span>↗</span></a><a className="text-link" href="#framework">Pelajari pendekatannya <span>↓</span></a></div><div className="trust-row"><span>Berbasis riset</span><i /><span>Insight yang actionable</span><i /><span>Privasi terjaga</span></div></div>
      <div className="hero-visual" aria-label="Preview dashboard hasil assessment"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="score-card"><div className="card-top"><span>Overall engagement</span><b>Q3 2026</b></div><div className="score-row"><div className="score-ring"><strong>82</strong><small>/100</small></div><div><p className="trend">↑ 8%</p><span>vs. periode lalu</span></div></div><div className="mini-bars" aria-hidden="true"><span style={{height:"46%"}}/><span style={{height:"58%"}}/><span style={{height:"52%"}}/><span style={{height:"70%"}}/><span style={{height:"67%"}}/><span style={{height:"82%"}}/></div></div><div className="pulse-card"><span className="pulse-icon">✦</span><div><b>Strongest signal</b><strong>Shared Mission</strong></div></div><div className="people-card"><div className="avatars"><span>AR</span><span>DN</span><span>MK</span></div><div><strong>94%</strong><small>response rate</small></div></div></div>
    </section>
    <section className="definition" id="manfaat"><div className="section-kicker">Definisi engagement</div><div className="definition-grid"><h2>Lebih dari sekadar<br /><em>kepuasan kerja.</em></h2><div><p>Employee engagement adalah keterikatan psikologis karyawan terhadap pekerjaan, tim, dan organisasi—tercermin dari keterlibatan dan antusiasme mereka dalam bekerja.</p><p>Ia mengukur investasi emosional dan psikologis: seberapa dalam seseorang peduli, berkontribusi, dan bersedia melampaui ekspektasi karena ingin, bukan karena terpaksa.</p></div></div><div className="commitment-row"><article><span>01</span><h3>Emotional Commitment</h3><p>Hubungan emosional yang kuat dengan pekerjaan dan kesuksesan organisasi.</p></article><article><span>02</span><h3>Psychological Investment</h3><p>Kemauan mental untuk berpikir, berkontribusi, dan terus meningkatkan kinerja.</p></article><article><span>03</span><h3>Discretionary Effort</h3><p>Energi ekstra yang diberikan dengan sukarela, jauh melampaui deskripsi pekerjaan.</p></article></div></section>
    <section className="impact-section"><div className="impact-intro"><p className="eyebrow light"><span /> Dampak bisnis nyata</p><h2>Engagement bukan soft metric.</h2><p>Unit bisnis dengan engagement tertinggi konsisten mengungguli kelompok terbawah. Data berikut merangkum temuan Gallup.</p></div><div className="impact-grid">{impacts.map(([value,direction,label]) => <article key={label}><strong>{value}</strong><span>{direction}</span><p>{label}</p></article>)}</div><div className="impact-note"><span>+10%</span> kepuasan pelanggan <i /> <span>−32%</span> cacat kualitas <i /> <span>−63%</span> insiden keselamatan</div></section>
    <section className="framework-section" id="framework"><div className="section-heading"><div><p className="section-kicker">Kerangka Q12</p><h2>12 faktor penentu.<br />4 area yang saling menguatkan.</h2></div><p>Engagement tidak dibentuk oleh satu hal. Assessment ini membaca pengalaman karyawan secara menyeluruh—mulai dari fondasi untuk bekerja hingga alasan mereka memilih bertumbuh bersama organisasi.</p></div><div className="pillar-grid">{pillars.map((pillar,index) => <label className={`pillar pillar-${index+1}`} key={pillar.name}><input className="pillar-toggle" type="checkbox" aria-label={`Pilih area ${pillar.name}`} /><div className="pillar-index">{pillar.number}</div><p className="pillar-label">{pillar.label}</p><h3>{pillar.name}</h3><p className="pillar-copy">{pillar.copy}</p><div className="question-tags">{pillar.qs.map(q => <span key={q[0]}><b>{q[0]}</b>{q[1]}</span>)}</div></label>)}</div></section>
    <section className="signals-section" id="insight"><div className="signals-header"><div><p className="eyebrow light"><span /> 12 pertanyaan assessment</p><h2>Pertanyaan yang tepat membuka percakapan yang penting.</h2></div><p>Setiap jawaban membantu melihat pengalaman karyawan dengan lebih jernih—apa yang sudah kuat, apa yang selama ini menghambat, dan perubahan mana yang paling layak diprioritaskan.</p></div><div className="signal-groups">{signalGroups.map(group => <section className="signal-group" key={group.number}><header><span>{group.number}</span><div><h3>{group.title}</h3><p>{group.subtitle}</p></div></header><div className="signal-list">{group.items.map(([q,title,copy]) => <details key={q}><summary><span>{q}</span><strong>{title}</strong><i>+</i></summary><p>{copy}</p></details>)}</div></section>)}</div></section>
    <section className="connected-section"><div className="connected-copy"><p className="section-kicker">Insight terintegrasi</p><h2>Setiap sinyal saling terhubung.</h2><p>Kejelasan ekspektasi memperkuat penggunaan talenta. Pengakuan membangun ikatan tim. Dukungan membuka ruang untuk pertumbuhan. Karena itu, kami tidak membaca skor secara terpisah—kami menemukan pola di balik pengalaman karyawan Anda.</p><ul><li><b>Diagnose</b><span>Temukan akar hambatan engagement.</span></li><li><b>Prioritize</b><span>Fokus pada intervensi dengan dampak terbesar.</span></li><li><b>Progress</b><span>Ukur perubahan dan lanjutkan yang bekerja.</span></li></ul></div><div className="connection-map" aria-label="Keterkaitan empat aspek engagement"><div className="map-center"><span>Employee</span><strong>Engagement</strong></div>{["Basic Needs","Contribution","Teamwork","Growth"].map((item,i) => <div className={`map-node node-${i+1}`} key={item}><small>0{i+1}</small>{item}</div>)}<div className="map-line line-1"/><div className="map-line line-2"/><div className="map-line line-3"/><div className="map-line line-4"/></div></section>
    <section className="cta-section" id="contact"><div><p className="eyebrow light"><span /> Mulai dari percakapan</p><h2>Temukan apa yang membuat<br />tim Anda benar-benar terlibat.</h2></div><div className="cta-action"><p>Kami bantu merancang assessment, membaca pola, dan menerjemahkan hasilnya menjadi langkah yang dapat dilakukan.</p><a className="button" href="mailto:hello@incentric.id?subject=Employee%20Engagement%20Assessment">Jadwalkan konsultasi <span>↗</span></a></div></section>
    <footer><a className="brand footer-brand" href="#top"><span className="brand-mark">i</span><span>incentric <b>engage</b></span></a><p>Employee Engagement Assessment</p><a href="#top">Kembali ke atas ↑</a></footer>
  </main>;
}
