import type { Metadata } from "next";

export const metadata: Metadata = { title: "Employee Engagement Assessment | Incentric", description: "Pahami faktor yang membuat karyawan peduli pada pekerjaan dan berkomitmen pada hasilnya, lalu tentukan tindak lanjut yang lebih terarah." };

const whatsappUrl = "https://api.whatsapp.com/send?phone=6281249017400&text=Halo%2C%20saya%20ingin%20bertanya%20lebih%20lanjut%20tentang%20Employee%20Engagement%20ini";

const impacts = [["78%", "lebih sedikit", "ketidakhadiran"], ["23%", "lebih tinggi", "profitabilitas"], ["18%", "lebih tinggi", "penjualan"], ["14%", "lebih tinggi", "produktivitas"]];
const caseStudies = [
  { company: "Nationwide", context: "Jasa keuangan · 26.000 karyawan", result: "2×", resultLabel: "kepedulian dan komitmen dibanding populasi pekerja secara umum", copy: "Assessment pertama menempatkan Nationwide di persentil ke-37. Perusahaan lalu membuka hasilnya kepada karyawan, melatih para manajer, dan menyusun rencana tindak lanjut di setiap tim. Gallup mencatat kenaikan lebih dari 10 poin pada tahun pertama. Pada 2019, proporsi karyawan yang peduli dan berkomitmen di Nationwide mencapai dua kali lipat populasi pekerja secara umum.", source: "https://www.gallup.com/workplace/352415/why-nationwide-one-engaged-companies-world.aspx" },
  { company: "NFU Mutual", context: "Asuransi · Perubahan jangka panjang", result: "P99", resultLabel: "selama enam tahun berturut-turut", copy: "NFU Mutual mulai menggunakan Q12 pada 2011. Mereka mencapai target persentil ke-90 satu tahun lebih cepat, kemudian mempertahankan persentil ke-99 selama enam tahun. Kuncinya: kepedulian dan komitmen dibahas dalam pekerjaan sehari-hari, bukan hanya saat survei tahunan.", source: "https://www.gallup.com/workplace/514328/nfu-mutual-success-story.aspx" },
  { company: "Mutual of Omaha", context: "Asuransi · Perubahan budaya", result: "+63%", resultLabel: "kenaikan proporsi karyawan yang peduli dan berkomitmen", copy: "Setiap manajer menerima hasil tim, membahasnya bersama karyawan, lalu bertanggung jawab atas rencana tindak lanjut. Dalam satu tahun, tingkat partisipasi naik dari 89% menjadi 94%, sementara proporsi karyawan yang peduli dan berkomitmen meningkat 63%.", source: "https://news.gallup.com/businessjournal/11608/mutual-omahas-healthy-preoccupation-talent.aspx" },
];
const pillars = [
  { number: "01", name: "Basic Needs", label: "Dasar untuk bekerja dengan baik", copy: "Karyawan perlu tahu apa yang diharapkan dari mereka dan memiliki dukungan yang cukup untuk menyelesaikan pekerjaan.", qs: [["Q1", "Ekspektasi yang jelas"], ["Q2", "Dukungan kerja yang memadai"]] },
  { number: "02", name: "Individual Contribution", label: "Kontribusi yang terasa berarti", copy: "Karyawan lebih peduli dan berkomitmen ketika dapat menggunakan kekuatan terbaiknya dan menerima apresiasi atas pekerjaan yang dilakukan.", qs: [["Q3", "Kesempatan menggunakan kekuatan"], ["Q4", "Apresiasi atas kontribusi"]] },
  { number: "03", name: "Teamwork", label: "Hubungan di dalam tim", copy: "Kepedulian, kepercayaan, dan tujuan bersama membantu tim bekerja lebih terbuka dan menjaga standar kualitas.", qs: [["Q5", "Kepedulian"], ["Q6", "Dukungan untuk berkembang"], ["Q7", "Pendapat didengar"], ["Q8", "Tujuan yang bermakna"], ["Q9", "Komitmen pada kualitas"], ["Q10", "Hubungan antarrekan"]] },
  { number: "04", name: "Growth", label: "Kesempatan untuk berkembang", copy: "Percakapan tentang kemajuan dan kesempatan belajar membantu karyawan melihat masa depan mereka di organisasi.", qs: [["Q11", "Pembahasan perkembangan"], ["Q12", "Kesempatan belajar"]] },
];
const signalGroups = [
  { number: "01", title: "Basic Needs", subtitle: "Kejelasan peran dan dukungan kerja", items: [
    ["Q1", "Ekspektasi yang Jelas", "Saya memahami hasil, tanggung jawab, dan prioritas yang diharapkan dari saya."],
    ["Q2", "Dukungan Kerja yang Memadai", "Saya memiliki alat, informasi, dan dukungan yang dibutuhkan untuk bekerja dengan baik."],
  ]},
  { number: "02", title: "Individual Contribution", subtitle: "Kesempatan berkontribusi dan mendapat apresiasi", items: [
    ["Q3", "Kesempatan Menggunakan Kekuatan", "Dalam pekerjaan sehari-hari, saya memiliki kesempatan untuk menggunakan kemampuan terbaik saya."],
    ["Q4", "Apresiasi atas Kontribusi", "Pekerjaan yang saya lakukan dengan baik mendapat pengakuan atau apresiasi."],
  ]},
  { number: "03", title: "Teamwork", subtitle: "Kepedulian, kepercayaan, dan tujuan bersama", items: [
    ["Q5", "Kepedulian sebagai Individu", "Atasan atau rekan kerja menunjukkan kepedulian kepada saya sebagai individu."],
    ["Q6", "Dukungan untuk Berkembang", "Ada seseorang di tempat kerja yang mendorong saya untuk terus berkembang."],
    ["Q7", "Pendapat yang Didengar", "Pendapat saya didengar dan dipertimbangkan dalam keputusan yang berkaitan dengan pekerjaan saya."],
    ["Q8", "Tujuan yang Bermakna", "Misi organisasi membuat pekerjaan saya terasa penting dan bermakna."],
    ["Q9", "Komitmen pada Kualitas", "Rekan kerja saya memiliki komitmen yang sama untuk menghasilkan pekerjaan berkualitas."],
    ["Q10", "Hubungan Antar-rekan", "Saya memiliki hubungan yang dekat dan saling percaya dengan orang-orang di tempat kerja."],
  ]},
  { number: "04", title: "Growth", subtitle: "Umpan balik dan kesempatan belajar", items: [
    ["Q11", "Pembahasan tentang Perkembangan", "Dalam enam bulan terakhir, seseorang membahas kemajuan dan perkembangan saya."],
    ["Q12", "Kesempatan untuk Belajar", "Dalam setahun terakhir, saya mendapat kesempatan yang berarti untuk belajar dan mengembangkan diri."],
  ]},
];

export default function Home() {
  return <main>
    <nav className="nav-shell" aria-label="Navigasi utama"><a className="brand" href="#top" aria-label="Incentric beranda"><img className="brand-logo" src="/incentric-logo-blue.png" alt="Incentric Beyond Experience" /></a><div className="nav-links"><a href="#manfaat">Mengapa penting</a><a href="#case-studies">Studi kasus</a><a href="#framework">Yang diukur</a><a href="#insight">12 pertanyaan</a></div><a className="button button-small" href={whatsappUrl} target="_blank" rel="noreferrer">Bahas assessment</a></nav>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span /> Employee Engagement Assessment</p><h1>Ketahui faktor yang membangun kepedulian dan komitmen tim Anda.</h1><p className="hero-lede">Pahami bagaimana karyawan memaknai pekerjaan mereka, mulai dari kejelasan peran hingga kesempatan berkembang. Hasilnya membantu Anda melihat apa yang perlu diperbaiki dan menentukan langkah berikutnya.</p><div className="hero-actions"><a className="button" href={whatsappUrl} target="_blank" rel="noreferrer">Bahas kebutuhan assessment <span>↗</span></a><a className="text-link" href="#framework">Lihat yang diukur <span>↓</span></a></div><div className="trust-row"><span>12 aspek terukur</span><i /><span>Ringkasan per area</span><i /><span>Prioritas tindak lanjut</span></div></div>
      <div className="hero-visual" aria-label="Contoh dashboard hasil assessment"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="score-card"><div className="card-top"><span>Skor kepedulian & komitmen</span><b>Data ilustrasi</b></div><div className="score-row"><div className="score-ring"><strong>82</strong><small>/100</small></div><div><p className="trend">↑ 8%</p><span>dibanding periode lalu</span></div></div><div className="mini-bars" aria-hidden="true"><span style={{height:"46%"}}/><span style={{height:"58%"}}/><span style={{height:"52%"}}/><span style={{height:"70%"}}/><span style={{height:"67%"}}/><span style={{height:"82%"}}/></div></div><div className="pulse-card"><span className="pulse-icon">✦</span><div><b>Area terkuat</b><strong>Tujuan bersama</strong></div></div><div className="people-card"><div className="avatars"><span>AR</span><span>DN</span><span>MK</span></div><div><strong>94%</strong><small>tingkat partisipasi</small></div></div></div>
    </section>
    <section className="definition" id="manfaat"><div className="section-kicker">Apa arti engagement bagi tim Anda?</div><div className="definition-grid"><h2>Karyawan yang terlihat baik belum tentu <em>peduli dan berkomitmen.</em></h2><div><p>Dalam assessment ini, engagement berarti seberapa kuat karyawan peduli pada pekerjaan, tim, dan organisasi, serta bersedia memberi kontribusi terbaik.</p><p>Karyawan yang peduli dan berkomitmen memahami perannya, merasa kontribusinya berarti, dan mau ikut menjaga hasil bersama.</p></div></div><div className="commitment-row"><article><span>01</span><h3>Peduli pada hasil</h3><p>Karyawan melihat hubungan antara pekerjaannya dan keberhasilan tim atau organisasi.</p></article><article><span>02</span><h3>Mau berkontribusi</h3><p>Karyawan menggunakan kemampuan dan idenya untuk membantu pekerjaan berjalan lebih baik.</p></article><article><span>03</span><h3>Berkomitmen memberi yang terbaik</h3><p>Karyawan mengambil inisiatif ketika situasi membutuhkannya, bukan hanya menjalankan tugas minimum.</p></article></div></section>
    <section className="urgency-section"><div className="urgency-heading"><div><p className="section-kicker">State of the Global Workplace 2026</p><h2>Sebagian besar karyawan belum cukup peduli dan berkomitmen pada pekerjaannya.</h2></div><p>Pada 2025, hanya 20% karyawan global yang tergolong engaged, artinya, mereka peduli pada pekerjaan dan berkomitmen memberi usaha terbaik. Di Asia Tenggara angkanya 25%. Data ini tidak menjelaskan kondisi tim Anda, tetapi menunjukkan mengapa kondisi tersebut perlu diukur.</p></div><div className="urgency-stats"><article><strong>20%</strong><span>karyawan global yang peduli dan berkomitmen</span><small>Turun dari 23% pada 2023</small></article><article><strong>64%</strong><span>belum merasa terhubung kuat</span><small>Bekerja, tetapi belum menunjukkan kepedulian dan komitmen yang kuat</small></article><article><strong>40%</strong><span>mengalami stres harian</span><small>Mengaku mengalami stres sepanjang sebagian besar hari sebelumnya</small></article><article className="sea-stat"><strong>25%</strong><span>peduli dan berkomitmen di Asia Tenggara</span><small>Artinya, tiga dari empat karyawan belum menunjukkan kepedulian dan komitmen yang kuat</small></article></div><div className="urgency-action"><p>Data global tidak dapat menunjukkan apa yang terjadi di organisasi Anda. <b>Assessment memberi titik awal yang lebih jelas untuk menentukan tindakan.</b></p><a className="button" href={whatsappUrl} target="_blank" rel="noreferrer">Petakan kondisi tim <span>↗</span></a></div><a className="source-link" href="https://www.gallup.com/workplace/697904/state-of-the-global-workplace-global-data.aspx" target="_blank" rel="noreferrer">Sumber: Gallup, State of the Global Workplace 2026 ↗</a></section>
    <section className="impact-section"><div className="impact-intro"><p className="eyebrow light"><span /> Dampak pada bisnis</p><h2>Kepedulian dan komitmen terlihat dalam hasil kerja.</h2><p>Meta-analisis Gallup terhadap puluhan ribu unit bisnis di 90 negara menemukan bahwa unit dengan tingkat engagement tinggi, karena karyawan yang peduli dan berkomitmen memiliki hasil yang lebih baik daripada unit di kuartil terbawah.</p></div><div className="impact-grid">{impacts.map(([value,direction,label]) => <article key={label}><strong>{value}</strong><span>{direction}</span><p>{label}</p></article>)}</div><div className="impact-note"><span>+10%</span> loyalitas pelanggan <i /> <span>−32%</span> cacat kualitas <i /> <span>−63%</span> insiden keselamatan</div><a className="source-link source-dark" href="https://www.gallup.com/workplace/321725/gallup-q12-meta-analysis-report.aspx" target="_blank" rel="noreferrer">Sumber: Gallup Q12 Meta-Analysis, edisi ke-11 ↗</a></section>
    <section className="case-section" id="case-studies"><div className="case-heading"><div><p className="section-kicker">Belajar dari organisasi lain</p><h2>Apa yang berubah ketika hasil assessment ditindaklanjuti?</h2></div><p>Ketiga organisasi ini memulai dari kondisi yang berbeda. Kesamaannya ada pada tindak lanjut: hasil dibuka kepada karyawan, manajer dilibatkan, dan kemajuan dipantau dari waktu ke waktu.</p></div><div className="case-grid">{caseStudies.map((study,index) => <article className="case-card" key={study.company}><div className="case-top"><span>0{index+1}</span><p>{study.context}</p></div><h3>{study.company}</h3><div className="case-result"><strong>{study.result}</strong><span>{study.resultLabel}</span></div><p className="case-copy">{study.copy}</p><a href={study.source} target="_blank" rel="noreferrer">Baca studi Gallup <span>↗</span></a></article>)}</div><div className="case-lesson"><span>Pola yang terlihat</span><p>Survei memberi data. Perubahan terjadi ketika <b>manajer membahas hasilnya bersama tim, memilih fokus yang jelas, dan menindaklanjutinya.</b></p></div></section>
    <section className="framework-section" id="framework"><div className="section-heading"><div><p className="section-kicker">12 aspek kepedulian dan komitmen</p><h2>Lihat pengalaman karyawan dari empat area.</h2></div><p>Setiap area menjawab kebutuhan yang berbeda. Jika dibaca bersama, hasilnya menunjukkan bagian yang sudah kuat dan bagian yang perlu mendapat perhatian lebih dulu.</p></div><div className="pillar-grid">{pillars.map((pillar,index) => <article className={`pillar pillar-${index+1}`} key={pillar.name}><div className="pillar-index">{pillar.number}</div><p className="pillar-label">{pillar.label}</p><h3>{pillar.name}</h3><p className="pillar-copy">{pillar.copy}</p><div className="question-tags">{pillar.qs.map(q => <span key={q[0]}><b>{q[0]}</b>{q[1]}</span>)}</div></article>)}</div></section>
    <section className="signals-section" id="insight"><div className="signals-header"><div><p className="eyebrow light"><span /> Yang ditanyakan</p><h2>Dua belas pernyataan untuk membaca kepedulian dan komitmen karyawan.</h2></div><p>Buka setiap item untuk melihat pernyataan yang dinilai. Hasilnya dikelompokkan berdasarkan empat area agar tim Anda lebih mudah menemukan fokus pembahasan.</p></div><div className="signal-groups">{signalGroups.map(group => <section className="signal-group" key={group.number}><header><span>{group.number}</span><div><h3>{group.title}</h3><p>{group.subtitle}</p></div></header><div className="signal-list">{group.items.map(([q,title,copy]) => <details key={q}><summary><span>{q}</span><strong>{title}</strong><i>+</i></summary><p>{copy}</p></details>)}</div></section>)}</div></section>
    <section className="connected-section"><div className="connected-copy"><p className="section-kicker">Membaca hasil</p><h2>Skor baru berguna ketika polanya dibaca bersama.</h2><p>Kejelasan ekspektasi membantu karyawan menggunakan kekuatannya. Apresiasi memperkuat hubungan di dalam tim. Dukungan dari manajer membuka kesempatan berkembang. Karena itu, kami membaca hubungan antarskor, bukan hanya angka per pertanyaan.</p><ul><li><b>Temukan pola</b><span>Lihat area yang paling memengaruhi pengalaman kerja.</span></li><li><b>Tentukan fokus</b><span>Pilih tindak lanjut yang paling relevan bagi tim.</span></li><li><b>Pantau perubahan</b><span>Ukur kembali untuk melihat apa yang membaik.</span></li></ul></div><div className="connection-map" aria-label="Keterkaitan empat area kepedulian dan komitmen"><div className="map-center"><span>Kepedulian</span><strong>& komitmen</strong></div>{["Basic Needs","Individual Contribution","Teamwork","Growth"].map((item,i) => <div className={`map-node node-${i+1}`} key={item}><small>0{i+1}</small>{item}</div>)}<div className="map-line line-1"/><div className="map-line line-2"/><div className="map-line line-3"/><div className="map-line line-4"/></div></section>
    <section className="cta-section" id="contact"><div><p className="eyebrow light"><span /> Langkah berikutnya</p><h2>Mulai dengan gambaran yang jujur tentang seberapa peduli dan berkomitmen tim Anda.</h2></div><div className="cta-action"><p>Kami membantu menyiapkan assessment, merangkum temuan per area, dan menyusun prioritas yang dapat dibahas bersama para manajer.</p><a className="button" href={whatsappUrl} target="_blank" rel="noreferrer">Bahas kebutuhan assessment <span>↗</span></a></div></section>
    <footer><a className="brand footer-brand" href="#top"><img className="brand-logo" src="/incentric-logo-white.png" alt="Incentric Beyond Experience" /></a><p>Employee Engagement Assessment</p><a href="#top">Kembali ke atas ↑</a></footer>
  </main>;
}
