import type { Metadata } from "next";

export const metadata: Metadata = { title: "Employee Engagement Assessment | Incetric Engage", description: "Ukur keterlibatan karyawan melalui 12 sinyal utama dan temukan prioritas yang mendorong pertumbuhan organisasi." };

const impacts = [["78%", "lebih sedikit", "ketidakhadiran"], ["23%", "lebih tinggi", "profitabilitas"], ["18%", "lebih tinggi", "penjualan"], ["14%", "lebih tinggi", "produktivitas"]];
const pillars = [
  { number: "01", name: "Basic Needs", label: "Fondasi kerja", copy: "Kejelasan peran dan akses terhadap sumber daya yang membuat karyawan dapat bekerja tanpa hambatan.", qs: [["Q1", "Clarity of Expectations"], ["Q2", "Materials & Equipment"]] },
  { number: "02", name: "Individual Contribution", label: "Potensi individu", copy: "Kesempatan menggunakan kekuatan terbaik dan pengakuan yang tulus atas kontribusi setiap orang.", qs: [["Q3", "Utilization of Strengths"], ["Q4", "Recognition & Praise"]] },
  { number: "03", name: "Teamwork", label: "Koneksi & kolaborasi", copy: "Dukungan, rasa memiliki, suara yang didengar, dan misi bersama yang menguatkan kualitas tim.", qs: [["Q5", "Caring & Support"], ["Q6", "Development"], ["Q7", "Voice & Inclusion"], ["Q8", "Shared Mission"], ["Q9", "Quality"], ["Q10", "Friendships"]] },
  { number: "04", name: "Growth", label: "Masa depan", copy: "Percakapan kemajuan dan kesempatan belajar yang menjaga talenta terus tumbuh bersama organisasi.", qs: [["Q11", "Progress Discussions"], ["Q12", "Learn & Grow"]] },
];
const signals = [
  ["Q1", "Clarity of Expectations", "Saya memahami dengan jelas apa yang diharapkan dari peran saya."], ["Q2", "Access to Materials", "Saya memiliki materi dan peralatan untuk bekerja dengan kualitas terbaik."],
  ["Q3", "Utilization of Strengths", "Saya memiliki kesempatan untuk memberikan yang terbaik setiap hari."], ["Q4", "Recognition & Praise", "Kontribusi dan kinerja baik saya mendapat pengakuan yang tepat."],
  ["Q5", "Caring & Support", "Ada seseorang di tempat kerja yang peduli pada saya sebagai individu."], ["Q6", "Encouragement of Development", "Ada seseorang yang aktif mendorong saya untuk berkembang."],
  ["Q7", "Voice & Inclusion", "Pendapat saya didengar dan dipertimbangkan dalam keputusan."], ["Q8", "Shared Mission", "Misi organisasi membuat pekerjaan saya terasa penting dan bermakna."],
  ["Q9", "Commitment to Quality", "Rekan kerja saya berkomitmen menghasilkan kualitas terbaik."], ["Q10", "Workplace Friendships", "Saya memiliki hubungan personal yang kuat di tempat kerja."],
  ["Q11", "Progress Discussions", "Saya mendapat percakapan rutin tentang kemajuan dan perkembangan."], ["Q12", "Opportunities to Grow", "Saya memiliki kesempatan berharga untuk belajar dan bertumbuh."],
];

export default function Home() {
  return <main>
    <nav className="nav-shell" aria-label="Navigasi utama"><a className="brand" href="#top" aria-label="Incentric Engage beranda"><span className="brand-mark">i</span><span>incentric <b>engage</b></span></a><div className="nav-links"><a href="#manfaat">Manfaat</a><a href="#framework">Framework</a><a href="#insight">Insight</a></div><a className="button button-small" href="#contact">Jadwalkan Demo</a></nav>
    <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span /> Employee Engagement Assessment</p><h1>Bangun tim yang<br />hadir sepenuhnya.</h1><p className="hero-lede">Pahami apa yang benar-benar dirasakan karyawan. Ubah 12 sinyal engagement menjadi keputusan yang lebih tajam—dan tempat kerja yang membuat talenta terbaik ingin bertumbuh.</p><div className="hero-actions"><a className="button" href="#contact">Mulai Assessment <span>↗</span></a><a className="text-link" href="#framework">Pelajari pendekatannya <span>↓</span></a></div><div className="trust-row"><span>Berbasis riset</span><i /><span>Insight yang actionable</span><i /><span>Privasi terjaga</span></div></div>
      <div className="hero-visual" aria-label="Preview dashboard hasil assessment"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="score-card"><div className="card-top"><span>Overall engagement</span><b>Q3 2026</b></div><div className="score-row"><div className="score-ring"><strong>82</strong><small>/100</small></div><div><p className="trend">↑ 8%</p><span>vs. periode lalu</span></div></div><div className="mini-bars" aria-hidden="true"><span style={{height:"46%"}}/><span style={{height:"58%"}}/><span style={{height:"52%"}}/><span style={{height:"70%"}}/><span style={{height:"67%"}}/><span style={{height:"82%"}}/></div></div><div className="pulse-card"><span className="pulse-icon">✦</span><div><b>Strongest signal</b><strong>Shared Mission</strong></div></div><div className="people-card"><div className="avatars"><span>AR</span><span>DN</span><span>MK</span></div><div><strong>94%</strong><small>response rate</small></div></div></div>
    </section>
    <section className="definition" id="manfaat"><div className="section-kicker">Definisi engagement</div><div className="definition-grid"><h2>Lebih dari sekadar<br /><em>kepuasan kerja.</em></h2><div><p>Employee engagement adalah keterikatan psikologis karyawan terhadap pekerjaan, tim, dan organisasi—tercermin dari keterlibatan dan antusiasme mereka dalam bekerja.</p><p>Ia mengukur investasi emosional dan psikologis: seberapa dalam seseorang peduli, berkontribusi, dan bersedia melampaui ekspektasi karena ingin, bukan karena terpaksa.</p></div></div><div className="commitment-row"><article><span>01</span><h3>Emotional Commitment</h3><p>Hubungan emosional yang kuat dengan pekerjaan dan kesuksesan organisasi.</p></article><article><span>02</span><h3>Psychological Investment</h3><p>Kemauan mental untuk berpikir, berkontribusi, dan terus meningkatkan kinerja.</p></article><article><span>03</span><h3>Discretionary Effort</h3><p>Energi ekstra yang diberikan dengan sukarela, jauh melampaui deskripsi pekerjaan.</p></article></div></section>
    <section className="impact-section"><div className="impact-intro"><p className="eyebrow light"><span /> Dampak bisnis nyata</p><h2>Engagement bukan soft metric.</h2><p>Unit bisnis dengan engagement tertinggi konsisten mengungguli kelompok terbawah. Data berikut merangkum temuan Gallup.</p></div><div className="impact-grid">{impacts.map(([value,direction,label]) => <article key={label}><strong>{value}</strong><span>{direction}</span><p>{label}</p></article>)}</div><div className="impact-note"><span>+10%</span> kepuasan pelanggan <i /> <span>−32%</span> cacat kualitas <i /> <span>−63%</span> insiden keselamatan</div></section>
    <section className="framework-section" id="framework"><div className="section-heading"><div><p className="section-kicker">Framework Q12</p><h2>12 sinyal. 4 level.<br />Satu gambaran utuh.</h2></div><p>Assessment membaca engagement secara holistik—dari kebutuhan paling mendasar hingga peluang untuk bertumbuh. Setiap level saling menguatkan.</p></div><div className="pillar-grid">{pillars.map((pillar,index) => <article className={`pillar pillar-${index+1}`} key={pillar.name}><div className="pillar-index">{pillar.number}</div><p className="pillar-label">{pillar.label}</p><h3>{pillar.name}</h3><p className="pillar-copy">{pillar.copy}</p><div className="question-tags">{pillar.qs.map(q => <span key={q[0]}><b>{q[0]}</b>{q[1]}</span>)}</div></article>)}</div></section>
    <section className="signals-section" id="insight"><div className="signals-header"><div><p className="eyebrow light"><span /> Assessment signals</p><h2>Pertanyaan sederhana.<br />Insight yang mendalam.</h2></div><p>Buka setiap sinyal untuk melihat apa yang diukur. Jawaban yang terkumpul menunjukkan kekuatan tim sekaligus prioritas perbaikan yang paling berarti.</p></div><div className="signal-list">{signals.map(([q,title,copy]) => <details key={q}><summary><span>{q}</span><strong>{title}</strong><i>+</i></summary><p>{copy}</p></details>)}</div></section>
    <section className="connected-section"><div className="connected-copy"><p className="section-kicker">Insight terintegrasi</p><h2>Setiap sinyal saling terhubung.</h2><p>Kejelasan ekspektasi memperkuat penggunaan talenta. Pengakuan membangun ikatan tim. Dukungan membuka ruang untuk pertumbuhan. Karena itu, kami tidak membaca skor secara terpisah—kami menemukan pola di balik pengalaman karyawan Anda.</p><ul><li><b>Diagnose</b><span>Temukan akar hambatan engagement.</span></li><li><b>Prioritize</b><span>Fokus pada intervensi dengan dampak terbesar.</span></li><li><b>Progress</b><span>Ukur perubahan dan lanjutkan yang bekerja.</span></li></ul></div><div className="connection-map" aria-label="Keterkaitan empat aspek engagement"><div className="map-center"><span>Employee</span><strong>Engagement</strong></div>{["Basic Needs","Contribution","Teamwork","Growth"].map((item,i) => <div className={`map-node node-${i+1}`} key={item}><small>0{i+1}</small>{item}</div>)}<div className="map-line line-1"/><div className="map-line line-2"/><div className="map-line line-3"/><div className="map-line line-4"/></div></section>
    <section className="cta-section" id="contact"><div><p className="eyebrow light"><span /> Mulai dari percakapan</p><h2>Temukan apa yang membuat<br />tim Anda benar-benar terlibat.</h2></div><div className="cta-action"><p>Kami bantu merancang assessment, membaca pola, dan menerjemahkan hasilnya menjadi langkah yang dapat dilakukan.</p><a className="button" href="mailto:hello@incentric.id?subject=Employee%20Engagement%20Assessment">Jadwalkan konsultasi <span>↗</span></a></div></section>
    <footer><a className="brand footer-brand" href="#top"><span className="brand-mark">i</span><span>incentric <b>engage</b></span></a><p>Employee Engagement Assessment</p><a href="#top">Kembali ke atas ↑</a></footer>
  </main>;
}
